# Generated by Django 2.2.9 on 2020-02-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbengine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DBEngine',
            new_name='DBEngines',
        ),
    ]
