# Generated by Django 2.2.9 on 2020-02-02 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, default='1.0', max_length=255, null=True)),
                ('technology', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('tool', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('stack', models.BooleanField(default=False)),
                ('multiple_db', models.BooleanField(default=False)),
                ('db_engine', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('db_dump', models.CharField(blank=True, max_length=255, null=True)),
                ('git_repo', models.TextField(blank=True, null=True)),
                ('dockerized', models.BooleanField(default=False)),
                ('admin_panel', models.BooleanField(blank=True, default=False)),
                ('product', models.CharField(blank=True, default='-', max_length=255)),
                ('output', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('request_log', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_creator', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_app', to='projects.Projects')),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'apps',
            },
        ),
    ]
