# Generated by Django 2.2.9 on 2020-02-02 02:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='Attributes',
        ),
        migrations.RenameModel(
            old_name='Entity',
            new_name='Entities',
        ),
    ]
