# Generated by Django 2.2.9 on 2020-02-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20200201_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='is_auto_increment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='is_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='is_null',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='is_primary_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
