# Generated by Django 2.2.9 on 2020-02-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tech',
            new_name='Techs',
        ),
    ]
